### PR TITLE
Annotate ontology roots with IAO_0000700

### PR DESCRIPTION
**Pull request by cthoyt**
Related to https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2149

## What this Does

Applies the annotation property [has ontology root term (IAO:0000700)](http://purl.obolibrary.org/obo/IAO_0000700) four times as the ontology level to list the four root terms:

1. SO:0000400
2. SO:0001260
3. SO:0000110
4. SO:0001060

It's true that this is already logically the root element, but this makes it explicit. This isn't actually the case for all ontologies.

## Why this is helpful

- the Ontology Lookup Service uses this to help better display ontologies
- if any of the four terms mentioned above are ever aligned with an upper ontology like BFO, it still will be the thing shown on OLS as the "root"
- this will be generally useful for things like alignment with COB since it makes it easier to figure out where the work will be

cc @matentzn

### CODE REVIEW

**Comment by erik-whiting** [comment]
I'm just curious, how were you able to tell that `SO:0000400`, `SO:0001260`, `SO:0000110`, and `SO:0001060` were roots? Is there a parser than deduces that or do you just kinda get a sixth sense for it after a while?

**Comment by matentzn** [comment]
@erik-whiting - see for example here: https://www.ebi.ac.uk/ols/ontologies/so

If you open the ontology you will see the roots.

**Comment by cthoyt** [comment]
@erik-whiting Nico is correct, some ontologies actually don't use an upper level hierarchy like BFO and just have some "naked" root entities and therefore are obvious from OLS. More generally though I implemented the code that generates the analysis at https://cthoyt.com/cob-root-analysis to identify these systematically.

**Comment by cthoyt** [comment]
@egchristensen can you take a look at this, please?

**Comment by cthoyt** [comment]
@davidwsant can you take a look at this, please?

**Comment by davidwsant** [comment]
Hi @cthoyt 
I have taken your pull request and run the Makefile to perpetuate the updates to the remaining files. Is this sufficient? I am going to close out the issue, but if anything else needs to be added you can re-open it. Thank you.

**Comment by cthoyt** [comment]
@davidwsant I am not sure what happened here. I guess by looking at 5cb4669 that you copied my changes and made your own commit. This means that my pull request did not get merged. Typically when someone makes a contribution, you either accept the pull request then run additional pipelines, or you check out the pull request yourself and run the changes there. 

It appears you have taken my changes and removed my change history from them. This is bad for a few reasons:

1. It makes it more opaque how changes happen in the repository
2. It deprives contributors of credit for making contributions

There are a few ways you could alleviate this in the future:

1. Add documentation on how to run the build that you appeared to do, either in the README.md or a CONTRIBUTING.md file
2. Make expectations more clear about what should be done in pull requests
3. If you're not familiar with git, I am happy to help teach you how to avoid this in the future

**Comment by cthoyt** [comment]
@davidwsant thanks for the quick turnaround. I hope you also have some time to consider my other PRs, which all make minor improvements to this great ontology

**Comment by davidwsant** [comment]
I apologize, I am still learning to use GitHub. I think the other SO members are better at this than I am, but since there were no conflicts this one was straight forward. Thanks for explaining it.

**Pull request merged**
